### ISSUE TITLE
fail to switch to another language for news

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#68]
https://preview-wmahkwebmain.gatsbyjs.io/news/wyng-masters-award-2012-poverty-finalists-announced
I cannot switch to another language for news pages , it shows 404

**Comment by shibacomputer** [comment]
These are CMS issues. As discussed in Marseille, this occurs when the slug of the pages don't match between English and Chinese.

For example, the news post you provided: https://kodak.ndc.tools/news/wyng-masters-award-winners-announced-poverty/
https://kodak-admin.ndc.tools/admin/content-manager/collectionType/api::news-post.news-post/90?plugins[i18n][locale]=en&plugins[i18n][relatedEntityId]=205

English:
![image](https://github.com/newdesigncongress/wma-hk-web/assets/737950/0de6abdc-da05-477a-b884-6ab92b073047)

Chinese:
![image](https://github.com/newdesigncongress/wma-hk-web/assets/737950/a2c0189b-67b0-407a-a056-19d082bf53eb)


Note the differing slug. I have fixed this one, but encourage you and the team to check the instances where pages 404 when switching, because this is fixable in the CMS.

**Comment by ClauLung** [comment]
For example in Island , the 2nd news- Curatorial Statement: Island(ed), I checked in CMS , the EN & CH slug is the same but it still shows 404 
![Screenshot 2023-09-06 at 9 37 59 AM](https://github.com/newdesigncongress/wma-hk-web/assets/95728978/0f253fd2-226b-4a0f-8c0f-f78a0f77236e)

**Comment by shibacomputer** [comment]
https://kodak.ndc.tools/news/curatorial-statement-island/
